<univ>
<uname>savitri</uname>
<city>shrdi</city>
<Rank>1</Rank>
</univ>
<univ>
<uname>savitri</uname>
<city>shrdi</city>
<Rank>1</Rank>
</univ>
<univ>
<uname>savitri</uname>
<city>shrdi</city>
<Rank>1</Rank>
</univ>